# Generated by Django 4.2.12 on 2024-12-08 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
    ]
