# Generated by Django 4.2.12 on 2024-12-08 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_bus_description_bus_image'),
        ('reviews', '0009_review_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.bus'),
            preserve_default=False,
        ),
    ]
