# Generated by Django 4.2.12 on 2024-12-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seat',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
