# Generated by Django 4.2.12 on 2024-12-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_bus_seat_delete_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='description',
            field=models.CharField(default='free snack', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1603521801204-8d9c70dd08c8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YnVzJTIwaW5kb25lc2lhfGVufDB8fDB8fHww'),
            preserve_default=False,
        ),
    ]
